### ISSUE TITLE
Pcmu 

### ISSUE THREAD

**Issue by srmkv** [sp4rkie/pcap2audio#1]
hi, can you tell me what is needed for the script to understand pcmu?

**Comment by sp4rkie** [comment]
you could convert pcmu to wav. e.g. like this https://stackoverflow.com/questions/11666174/pcmu-to-wav-conversion

**Comment by srmkv** [comment]
I have the following problem, I need to extract the conversations separately from the pcap file. I do not get you, https://gist.github.com/avimar/d2e9d05e082ce273962d742eb9acac16

but it gives out one track, how do I split the wav recordings?

**Comment by sp4rkie** [comment]
in my program line 92 encomment the following line:

    ex("rm " fname_pfx "_f.wav" " " fname_pfx "_r.wav", 0)

to keep the data where both conversations are still separated.
